version: '2'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youtube-dl
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.11
    environment:
      - RABBITMQ_DEFAULT_USER=zoxon470
      - RABBITMQ_DEFAULT_PASS=zoxon470
    ports:
      - "5673:5672"
  web:
    restart: always
    build: .
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
  celery:
    restart: always
    build: .
    environment:
      - BROKER_URL=amqp://zoxon470:zoxon470@rabbit:5672/
      - CELERY_RESULT_BACKEND=amqp
    command: celery -A project worker -l info
    volumes:
      - /usr/src/app
    depends_on:
      - rabbit
